Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:00
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.info"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:01
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.net"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:02
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.org"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:03
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:04
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:05
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:06
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:07
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:08
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:09
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:10
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:11
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.ch"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:12
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.biz"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:13
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:14
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:15
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:16
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:17
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:18
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:19
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:20
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:21
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:22
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:23
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:24
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:25
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:26
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:27
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:28
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:29
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:30
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:31
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:32
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:33
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:34
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:35
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:36
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:37
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:38
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:39
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:40
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:41
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:42
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:43
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:44
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:45
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:46
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:47
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:48
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:49
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:50
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.nl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:51
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:52
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:53
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:54
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:55
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:56
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:57
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:58
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:59
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:60
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:61
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:62
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:63
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:64
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:65
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:66
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:67
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:68
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:69
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:70
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:71
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:72
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:73
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:74
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:75
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:76
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:77
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:78
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:79
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:80
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:81
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.at"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:82
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.be"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:83
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.de"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:84
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.pl"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:85
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastic.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:86
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-plastics.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:87
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymer.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:88
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo-polymers.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:89
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastic.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:90
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplastics.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:91
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymer.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:92
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeopolymers.jp"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:93
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo3dsolutions.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:94
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "mynexeoplastics.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:95
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeomaterials.co.uk"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:96
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeomaterials.mx"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:97
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeomaterials.tw"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:98
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeomaterials.us"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:99
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo3d.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:100
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo3d.net"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:101
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeo3dus.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:102
Add-DnsServerResourceRecordA -Name "host23" -ZoneName "nexeoplaschem.com"  -AllowUpdateAny -IPv4Address 	"IPADDRESSHERE"	 -TimeToLive 01:00:103
